### PR TITLE
post diffs on pr

### PR DESCRIPTION
**Pull request by nikandfor**

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@nikandfor this is looking good!

Can we make some small stylistic changes please: 

- Remove the "language" title, and instead render the title for each stage as "Stage 2: match_digit (go)"
- Make the diff comment marker a HTML comment, so that it isn't visible to the user. 
- Link to the workflow file instead of `codecrafters-io`

I've copy-pasted one comment and applied the changes as an example: https://github.com/codecrafters-io/build-your-own-grep/pull/11#issuecomment-1304818014.

**Review by rohitpaulk — APPROVED** [review]

**Comment by rohitpaulk** [comment]
@nikandfor quick note, it looks like this script posts a comment even if no diff files have changed (this can happen when we only update explanations, or change other files in the repository). Could you change it so that we only post a comment if something has changed?

**Comment by rohitpaulk** [comment]
@nikandfor quick note, it looks like this script posts a comment even if no diff files have changed (this can happen when we only update explanations, or change other files in the repository). Could you change it so that we only post a comment if something has changed?

**Comment by nikandfor** [comment]
Changed styling, added comment deletion if no diffs (if it was found), shouldn't add anything if there wasn't comment and no diffs.

Changes in already opened PRs with that workflow can be seen by just rerunning job in Github Actions panel.

**Review by rohitpaulk — APPROVED** [review]

**Comment by rohitpaulk** [comment]
@nikandfor looks good!

**Pull request merged**
